<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LARUOSJ" failures="2" tests="14" name="Authentication.authenticate" time="2.154" errors="0" timestamp="2025-06-11T15:48:04 NPT" skipped="0">
  <testcase classname="Authentication.authenticate" name="AuthenticateWithInvalidEmail" time="0.153"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithMissingSignature" time="0.139"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithNoLocation" time="0.087"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithEmptyEmail" time="0.419"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithEmptySignature" time="0.125"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithInvalidDevice" time="0.083"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithInvalidUserAgent" time="0.184"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticatewithValidCredentials" time="0.288">
    <failure message="fullname is missing expected object to not be null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: fullname is missing expected object to not be null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertNotNull(Assert.java:942)
at Authentication.authenticate.AuthenticatewithValidCredentials(authenticate.java:715)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- AuthenticatewithValidCredentials -->
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithWrongPin" time="0.087">
    <failure message="expected [VST_LOGIN_REMAINING_ATTEMPT_X] but found [VST_LOGIN_REMAINING_ATTEMPT_5]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [VST_LOGIN_REMAINING_ATTEMPT_X] but found [VST_LOGIN_REMAINING_ATTEMPT_5]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Authentication.authenticate.AuthenticateWithWrongPin(authenticate.java:860)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- AuthenticateWithWrongPin -->
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithEmptyPin" time="0.139"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithNoDevice" time="0.053"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithoutUserAgent" time="0.076"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithMissingPin" time="0.145"/>
  <system-out/>
  <testcase classname="Authentication.authenticate" name="AuthenticateWithInvalidPin" time="0.176"/>
  <system-out/>
</testsuite> <!-- Authentication.authenticate -->
